# Paths
X_TRAIN: "data/X_train.csv"
Y_TRAIN: "data/y_train.csv"
X_TEST: "data/X_test.csv"
MODEL_OUT: "models/"

# Random
SEED: 420

# Set this to your number of cores
N_JOBS: 6

# Data
TRAIN: 0.7
VAL: 0.2
PRE_TEST: 0

# Feature selection
LASSO:
  ALPHA: 0.01

# Models
XGBOOST:
  SELECTION:
    DEPTH: [3]
    LR: [0.05]
    N_CLASS: 5
    ROUNDS: 500
    SUBSET: 0.5
    SUBSAMPLE: 0.3
    IMP_THRESH: 0.0015
    CATEGORICAL: True
    MIN_CHILD_WGT: [15]

  PREDICTION:
    DEPTH: [3]
    LR: [0.05]
    N_CLASS: 5
    ROUNDS: 500
    SUBSET: 0.2
    SUBSAMPLE: 0.5
    CATEGORICAL: True
    MIN_CHILD_WGT: [30]

  STACK:
    DEPTH: [3]
    LR: [0.05]
    N_CLASS: 5
    ROUNDS: 500
    SUBSET: 1
    SUBSAMPLE: 1
    CATEGORICAL: True
    MIN_CHILD_WGT: [100]

SVM:
  SUBSAMPLE: 0.5
  ROUNDS: 10

NN:
  H_DIM: [128, 500, 1000, 500, 128]
  BATCH_SIZE: 512
  DROPOUT: 0.2
  EPOCHS: 1000
  LR: 0.002
  L2_REG: 0.01
  MOMENTUM: 0.9
  LR_CYCLE: 250

  RPROP_LR: 0.03

RF:
  N_TREES: 500
  MAX_FTRS: 0.6
  MAX_SAMPLES: 0.6
  MIN_CHILD_WGT: 30
  MAX_DEPTH: 15

KNN:
  NEIGHBORS: 500